config/routes.rb
SimpleBookshelf::Application.routes.draw do

  root :to => "books#index"

  
  resources :books do
    resources :authors, :only => :destroy

    member do
      get 'destroy_document'
    end

    collection do
      get 'similar'
    end
  end

  resources :formats, :except => [:new, :edit]

  resources :keywords, 
    :controller => :nested_tags,
    :only => [:index, :create, :update, :destroy]

  devise_for :users, :controllers => {:registrations => "users/registrations"}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  belongs_to :group

  validates_presence_of :group, :message => I18n.t("sb.user.validations.group_missing")

  def add_to_group(params)
  	return if params["id"].present? && params["name"].present?

    if params["id"] && params["id"].present?
  	 	self.group = Group.find(params["id"])
    end

    if params["name"] && params["name"].present?
  		group = Group.create(:name => params["name"])
		  self.group = group
      self.admin = true
    end
    
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

	def create
		build_resource
    resource.try(:add_to_group, params[:group])
    
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/users/_links.erb
<%- if controller_name != 'registrations' %>
	<%= link_to I18n.t("devise.links.sign_up"), new_user_registration_path %><br />
<% end -%>

<%- if controller_name != 'sessions' %>
  <%= link_to I18n.t("devise.links.sign_in"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to I18n.t("devise.forgot_password"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to I18n.t("devise.confirmations.not_received"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>