config/routes.rb
SimpleBookshelf::Application.routes.draw do

  root :to => "books#index"

  
  resources :books do
    resources :authors, :only => :destroy

    member do
      get 'destroy_document'
    end

    collection do
      get 'similar'
    end
  end

  resources :formats, :except => [:new, :edit]

  resources :keywords, 
    :controller => :nested_tags,
    :only => [:index, :create, :update, :destroy]

  devise_for :users, :controllers => {:registrations => "users/registrations"}

end

app/models/format.rb
class Format < ActiveRecord::Base

	################################
  ### ActiveRecord Associations ##
  ################################
  has_and_belongs_to_many :books

  attr_accessible :name
  
  validates_presence_of :name
  
end

app/controllers/formats_controller.rb
# encoding: utf-8

class FormatsController < ApplicationController

  before_filter :authenticate_admin

	def index
		@format = Format.new
	end

	def create
		@format = Format.new(params[:format]) if Format.find_by_name(params[:format][:name]).nil?
		if (!@format.nil? && @format.save)
			flash[:notice] = I18n.t("sb.flash.notices.create_format_success")
		else
			flash[:error] = I18n.t("sb.flash.errors.create_format_error")
		end

    redirect_to formats_path
	end
  
  def update
    begin
      @format = Format.find(params[:format][:id])
      @format.update_attributes(params[:format])
      flash[:notice] = I18n.t("sb.flash.notices.update_format_success")
      redirect_to formats_path
    rescue ActiveRecord::RecordNotFound
      flash[:error] = I18n.t("sb.flash.errors.update_format_error")
      redirect_to formats_path    
    end
  end
  
  def destroy
    begin
      @format = Format.find(params[:format][:id])
      @format.destroy
      flash[:notice] = I18n.t("sb.flash.notices.delete_format_success")
      redirect_to formats_path
    rescue ActiveRecord::RecordNotFound
      flash[:error] = I18n.t("sb.flash.errors.delete_format_error")
      redirect_to formats_path      
    end
  end

end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/views/formats/index.html.erb
<div id="new-format-form" class="section">
<h2><%= I18n.t("sb.headers.new_format") %></h2>
<%= simple_form_for(@format) do |f| %>
	<%= f.input :name, :label => I18n.t("sb.forms.labels.format_name") %>
	<%= f.submit I18n.t("sb.forms.buttons.create_format"), {
		:class => "btn btn-primary"
	}%>
<% end %>
</div>
<div id="update-format-form" class="section border">
<h2><%= I18n.t("sb.headers.update_format") %></h2>
<%= form_tag(format_path(1), :method => :put) do |f| %>
	<div>
		<%= label_tag "format-id-update", I18n.t("sb.forms.labels.format_select_format") %>
		<%= select(:format, :id, Format.all.collect {|fm| [fm.name,fm.id]}, 
			{:include_blank => I18n.t("sb.forms.select.blank_option")},
			{:id => "format-id-update"})
			%>
		<label for="name"><%= I18n.t("sb.forms.labels.format_update_name") %></label>
		<%= text_field :format, :name %>
	</div>
	<%= submit_tag I18n.t("sb.forms.buttons.update_format"), {:class => "btn btn-primary"}%>
<% end %>
</div>
<div id="delete-format-form" class="section border">
<h2><%= I18n.t("sb.headers.delete_format") %></h2>
<%= form_tag(format_path(1), :method => :delete) do |f| %>
	<div style="margin-bottom:10px;">
		<%= label_tag "format-id-delete", I18n.t("sb.forms.labels.format_select_format")  %>
		<%= select(:format, :id, Format.all.collect {|fm| [fm.name,fm.id]}, 
			{:include_blank => I18n.t("sb.forms.select.blank_option") },
			{:id => "format-id-delete"}) %>
	</div>
	<%= submit_tag I18n.t("sb.forms.buttons.delete_format"), {
		:class => "btn btn-primary"
	}%>
<% end %>
</div>