config/routes.rb
SimpleBookshelf::Application.routes.draw do

  root :to => "books#index"

  
  resources :books do
    resources :authors, :only => :destroy

    member do
      get 'destroy_document'
    end

    collection do
      get 'similar'
    end
  end

  resources :formats, :except => [:new, :edit]

  resources :keywords, 
    :controller => :nested_tags,
    :only => [:index, :create, :update, :destroy]

  devise_for :users, :controllers => {:registrations => "users/registrations"}

end

app/models/book.rb
# encoding: utf-8

class Book < ActiveRecord::Base

	################################
  ### ActiveRecord Associations ##
  ################################

  has_many :book_authors
  has_many :authors, :through => :book_authors

  has_many :entries
  has_many :groups, :through => :entries

  accepts_nested_attributes_for :authors,
    :reject_if => :has_no_author_or_publisher?, :allow_destroy => true

  has_and_belongs_to_many :nested_tags, :join_table => "books_nested_tags"
  has_and_belongs_to_many :formats


  ###############
  # Validations
  ###############

  validates_presence_of :title, :message => I18n.t("sb.book.validations.title_missing")
  validates_presence_of :year, :message =>  I18n.t("sb.book.validations.year_missing")
  validates_presence_of :publisher, :message => I18n.t("sb.book.validations.publisher_missing")
  validates_presence_of :authors, :message => I18n.t("sb.book.validations.author_missing")

  validates_associated :authors, :message => I18n.t("sb.book.validations.author_missing")

  # validates_attachment_content_type :document, :content_type => ['application/pdf'],
  # :allow_blank => true, :message => I18n.t("sb.book.validations.attachment_content_type")

  ###############
  # Scopes
  ###############

  default_scope :order => "title ASC"

  # Attention
  # Works only with tables of type = MyISAM
  scope :similar_title, lambda {|terms|
    terms = terms.split(" ").join(" +").insert(0,"+")
    {
    :select => "id,title",
    :conditions => ["MATCH (title) AGAINST (? IN BOOLEAN MODE)",terms]
    }
  }

  ##############
  # Paperclip
  ##############

  has_attached_file :document,
    :url => "/system/books/documents/:id/original/:basename.:extension",
    :path => ":rails_root/public/system/books/documents/:id/original/:basename.:extension"

  ##############
  # Thinking Sphinx
  ##############

  self.per_page = 20

  define_index do
  	indexes title, :sortable => true
  	indexes publisher, :sortable => true
  	indexes authors(:first_name), :as => :author_first_name, :sortable => true
  	indexes authors(:last_name), :as => :author_last_name, :sortable => true
    indexes authors(:full_name), :as => :author_full_name
    indexes authors(:full_name_reversed), :as => :author_full_name_reversed, :sortable => true
  	indexes formats.id, :as => :format_id
  	indexes nested_tags.id, :as => :tag_id
    indexes groups.id, :as => :group_id

    has year

    set_property :delta => true
  end

  #
  # Copy publisher name to author last name
  # and check if attribute is blank
  def has_no_author_or_publisher?(author)
    author["last_name"] = self.publisher if self.publisher_is_author
    author["last_name"].blank?
  end

  class << self

    def add_conditions(params, user)
    	conditions = {}
    	conditions[:tag_id] = params[:book][:tag] if params[:book] && params[:book][:tag].present?
    	conditions[:format_id] = params[:book][:format] if params[:book] && params[:book][:format].present?
      conditions[:group_id] = user.group_id

    	return conditions
    end

    def build_query_string(params)
      return "" if params[:query] && params[:query].strip.eql?("")
      fields = []

      if params[:choices] && Book.is_selected?(params[:choices][:author])
        fields = ["@author_first_name", "@author_last_name", "@author_full_name", "@author_full_name_reversed"]
      end

      fields << "@title" if params[:choices] && Book.is_selected?(params[:choices][:title])
      fields << "@publisher" if params[:choices] && Book.is_selected?(params[:choices][:publisher])

      fields.present? ? fields.join(" \"#{params[:query]}\" | ") + " \"#{params[:query]}\"" : params[:query]
    end

    def filter(params, user)
      result = Book.search(
                        build_query_string(params),
                        :page => params[:page] || 1,
                        :per_page => 20,
                        :sort_mode => params[:order] ? params[:order].to_sym : :asc,
                        :order => params[:sort] ? params[:sort].to_sym : :author_last_name,
                        :match_mode => :extended,
                        :conditions => add_conditions(params, user)
                        )
      return result
    end

    def is_selected?(choice)
    	choice && choice.eql?("1")
    end

  end
end

app/controllers/books_controller.rb
# encoding : utf-8

class BooksController < ApplicationController

	before_filter :authenticate_user_or_admin, :only => [:index, :show]
	before_filter :authenticate_admin, :only => [:new, :create, :edit, :update, :destroy]
	before_filter :delete_tag_in_use_fragment, :only => [:create, :update, :destroy]
	before_filter :delete_new_authors_from_params_hash, :only => [:create, :update]

	def index
		@books = Book.filter(params, current_person)
		@current_tag_id = params[:book] ? params[:book][:tag].to_i : 0
	end

	def show
		@book = Book.find(params[:id])
	end

	def new
		@book = Book.new
		@book.authors.build
	end

	def create
		@book = Book.new(params[:book])
    @book.groups << current_user.group

		if params[:book][:format_ids]
			@book.formats << Format.find(params[:book][:format_ids])
		end
    
    if params[:book][:nested_tag_ids]
    	begin
    		@book.nested_tags << NestedTag.find(params[:book][:nested_tag_ids])
    	rescue ActiveRecord::RecordNotFound
    		puts "Ignored tag that can´t be found"
    	end
    end

    if (@book.save)
    	flash[:notice] = I18n.t("sb.flash.notices.create_book_success")
      redirect_to books_path
    else
    	flash[:error] = I18n.t("sb.flash.errors.create_book_error")
      @book.authors.build
      render :action => "new"
    end
	end

	def edit
    @book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		
		unless (@book.nil?)
      @book.update_attributes(params[:book])
		end

    if params[:book][:format_ids]
    	@book.formats.clear
    	@book.formats << Format.find(params[:book][:format_ids])
    end
    
    if params[:book][:nested_tag_ids]
    	@book.nested_tags.clear
    	begin
    		@book.nested_tags << NestedTag.find(params[:book][:nested_tag_ids])
    	rescue ActiveRecord::RecordNotFound
    		puts "Ignored tag that can´t be found"
    	end
    end

    if (@book.save)
    	flash[:notice] = I18n.t("sb.flash.notices.update_book_success")
      redirect_to books_path
    else
    	flash[:error] = I18n.t("sb.flash.errors.update_book_error")
      render :action => "edit"
    end

	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy

		flash[:notice] = I18n.t("sb.flash.notices.delete_book_success")
		redirect_to books_path
	end

	def destroy_document
		@book = Book.find(params[:id])
		@book.document = nil
		@book.save(:validate => false)
		
		flash[:notice] = I18n.t("sb.flash.notices.delete_attachment_success")
		redirect_to edit_book_path(@book)
	end
  
  #####
  # Actions beyond REST
  
  def similar
    @books = Book.similar_title(params[:title])
    render :template => "books/similar", :layout => false
  end
  
  private
  
  def delete_tag_in_use_fragment
    expire_fragment(:controller => "books", 
    	:action => "new", 
    	:action_suffix => 'tag_in_use_selection')
  end

  def delete_new_authors_from_params_hash
  	params["book"]["authors_attributes"].delete("new_authors")
  end

	protected

	def authenticate_user_or_admin
		unless user_signed_in?
			redirect_to new_user_session_path 
		end
	end
end

app/helpers/books_helper.rb
# encoding: utf-8

module BooksHelper
  
  # Taken from Railscast #197
  # http://railscasts.com/episodes/197-nested-model-form-part-2?view=asciicast
  def add_new_author_fields(f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s + "/" + association.to_s.singularize + "_fields", :f => builder)
    end
  end

  def add_post_params(params)
    blackList = ["action", "controller", "order", "sort", "commit"]
    url_params = params["order"] && params["order"].downcase.eql?("asc") ? "&order=desc" : "&order=asc"  
    url_params += append(params, blackList)
    return url_params
  end

  def append(args, blackList, objectname = nil)
    str = ""
    args.each do |key, value|
      unless blackList.include?(key)
        if value.class.eql?(Hash) || value.class.eql?(ActiveSupport::HashWithIndifferentAccess)
          str += append(value, blackList, key)
        else
          if objectname
            str += "&#{objectname}[#{key}]=#{value}"
          else
            str += "&#{key}=#{value}"
          end
        end
      end
    end

    return str
  end
  
  def add_order_arrow(sort, params)
    if (params["sort"] && params["sort"].eql?(sort))
      (params["order"] && params["order"].present? && params["order"].downcase.eql?("asc")) ? image_tag("icons/bullet_arrow_up.png",:title=>"Sortierung absteigend") : image_tag("icons/bullet_arrow_down.png",:title=>"Sortierung aufsteigend") 
    end
  end


  # # Tree select
  # # @params
  # # filter_unused = Show only tags that are used by at least one book
  # #

  def tree_select(categories, model, name, level=-1, selected="", options={})
    option_tags = [[I18n.t("sb.forms.select.blank_option"), ""]]
    option_tags = option_tags + add_options(categories, level, options)

    select_options = {:id => "#{model}_#{name}"}
    select_options[:class] = "span5" if options[:multiple]
    select_options[:multiple] = options[:multiple] || false

    select_tag("#{model}[#{name}]", 
      options_for_select(option_tags, selected.to_s), 
      select_options
    )
  end

  #
  # Add all available categories and its children to an array
  #
  def add_options(categories, level, options={})
    option_tags = []

    if categories.length > 0
      level += 1 # keep position
      categories.collect do |cat|
        if display_category(cat, options)
          # Indentation
          indent = ""
          (0..level*2).each do |i|
            indent << "&#160;"
          end

          option_tags << [indent.html_safe + cat.name, cat.id.to_s]

          if cat.children.any?
            option_tags = option_tags + add_options(cat.children, level, options)
          end
        end

      end

    end

    option_tags
  end
  
  def display_category(cat, options={})
    return true unless options[:filter_unused]
    
    show = cat.books.size > 0
    if cat.parent_id = 0
      cat.children.each do |subcat| 
        show = subcat.books.size > 0
        break if show
      end
    end
    
    return show
  end
  
  def display_nested_tags(tags)
    li_tags = ""
    for tag in tags
      unless tag.parent.nil?
        li_tags << content_tag(:li, "#{tag.parent.name} > ")
      end
      li_tags << content_tag(:li) do
        link_to tag.name, books_path + "?query=&book[tag]=" + tag.id.to_s + "&choices[author]=1", :title => "Suche nach Keyword '#{tag.name}'"
      end
    end

    content_tag(:ul, li_tags.html_safe, :class => "tags")
  end
  
  def display_linked_authors(authors)
    authors = authors.sort_by { |a| a.last_name.downcase }
    linked_authors = authors.map { |author|
      link_to(author.full_name_reversed, books_path + "?query=#{author.last_name}&choices[author]=1&choices[publisher]=1", :class => "author", :title => "Suche nach Autor '#{author.last_name}'")
    }
    linked_authors.any? ? linked_authors.join(", ").html_safe : ""
  end
  
  def display_formats(book)
    html = book.formats.collect{ |format| 
      link_to format.name, books_path + "?query=&book[format]=#{format.id}"
    }.sort.join(", ")
    html ? html.html_safe : "keine"
  end
  
  def display_number(i)
    params[:page] = 1 unless params[:page]
    (i+(Book.per_page*(params[:page].to_i-1))+1).to_s
  end

  #
  # Add a citation in the following format
  # author1, author2 (year): title, publisher
  # 
  def cite(book)
    citation = String.new
    citation << book.authors.map { |a| a.full_name_reversed  }.join(" / ")
    citation << " (#{book.year}): "
    citation << book.title.strip
    citation << ", #{book.publisher.strip}"
  end

end

app/views/books/_details.html.erb
<div class="section">
	<h5><%= book.title %>
		<% if current_user.admin? -%>
			&#160;<%= link_to image_tag("icons/page_white_edit.png"),edit_book_path(book), :title => "Buch bearbeiten"%>
		<% end -%>
	</h5>
	<div class="author">von <%= display_linked_authors(book.authors)%></div>
</div>
<div class="section"><%= book.abstract %></div>
<div class="section border info">
	<h5 style="margin-bottom:10px">Information:</h5>
	<div>Herausgeber: <%= book.publisher %></div>
	<div>Erscheinungsjahr: <%= book.year %></div>
	<div>Publikationsart(en): <%= display_formats(book) %></div>
</div>
<div class="section border">
	<div class="keywords">
		<h5 style="margin-bottom:10px">Schlagworte:</h5>
		<%= display_nested_tags(book.nested_tags) %>
	</div>
</div>
<div class="section border">
	<div class="location">
		<h5 style="margin-bottom:10px">Aktueller Standort:</h5>
		<%= book.location.blank? ? "Keine Angabe" : book.location %>
	</div>
</div>
<div class="section border">
	<div class="citation">
		<h5 style="margin-bottom:10px">Zitation:</h5>
		<%= text_area_tag "citation", cite(book) %>
	</div>
</div>
<% if book.document.file? %>
<div class="section border">
	<div class="file">
	<h5 style="margin-bottom:10px">Dateianhang</h5>
	<div style="float:left;margin-right:10px">
		<%= link_to image_tag("icons/file_pdf.png"),book.document.url, :title => "Anhang herunterladen"%></div>
	<div><%= link_to book.document.original_filename, book.document.url, :title => "Anhang herunterladen" %></div>
</div>
<% end %>

app/views/books/_form.html.erb
<%= f.input :title, :label => I18n.t("sb.forms.labels.book_title"), 
	:input_html => {:class => "span5"} %>
<div id="similar_books" style="display:none"></div>
<%= f.input :year, :label => I18n.t("sb.forms.labels.book_year"), :input_html => { :style => "width:50px", :maxlength => "4" }%>
<%= f.input :publisher, :label => I18n.t("sb.forms.labels.book_publisher"), 
	:input_html => {:class => "span5"} %>

<!-- Formats -->
<label for="formats"><%= I18n.t("sb.forms.labels.book_select_formats") %></label>
<% Format.all(:order => "name ASC").each_with_index do |fm, i| -%>
	<% if i%3==0 -%>
		<div style="float:left;height:80px;margin-right:15px">
	<% end -%>
	<%= f.simple_fields_for fm do |ff| -%>
		<%= check_box_tag "book[format_ids][]",fm.id, book.formats.include?(fm) %>&#160;<%= fm.name %><br />
	<% end -%>
	<% if i+1 == Format.all.size || (i+1)%3==0 -%>
		</div>
	<% end -%>
<% end -%>

<!-- Tags -->
<div style="clear:left">
<label for="book_nested_tag_ids"><%= I18n.t("sb.forms.labels.book_select_tags") %></label>
	<%= partial "shared/tag_selection" %>
	<span class="help-block"><em><%= I18n.t("sb.forms.hints.book_multiple_tag_select") %></em></span>
	<%# Set selected tag on client because partial is cached %>
	<%= hidden_field_tag "tag_id",book.nested_tags.size > 0 ? book.nested_tags[0].id : 0%>
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function() {
			$('select#book_nested_tag_ids').val(parseInt($('#tag_id').val()));
		});
	</script>
</div>

<!-- Authors -->
<div class="section border">
	<h2><%= I18n.t("sb.forms.headers.authors") %></h2>
	<% if @book.errors && @book.errors.messages[:authors] %>
		<div class="control-group error">
			<label><%= @book.errors.messages[:authors][0] %></label>
		</div>
	<% end %>
	<div class="row">
		<div class="span0"><%= f.check_box :publisher_is_author %></div>
		<div class="span5"><%= f.label :publisher_is_author, 
			I18n.t("sb.forms.labels.book_publisher_is_author") %></div>
	</div>
	<div id="authors">
	<%= f.simple_fields_for :authors do |builder| %>
		<%= partial "authors/author_fields", :f => builder %>
	<% end %>
	</div>
	<div id="new_author_fields" style="display: none">
		<%= add_new_author_fields(f, :authors) %>
	</div>
	<div><%= link_to_function(I18n.t("sb.forms.buttons.add_new_author"), 
		"addNewAuthor(this)", {:class => "btn btn-primary"} ) %></div>
</div>

<!-- Location -->
<div class="section border">
	<%= f.input :abstract, :label => I18n.t("sb.forms.labels.book_abstract"), :input_html => {:style => "width: 400px;", :rows => 10} %>
	<%= f.input :location, :label => I18n.t("sb.forms.labels.book_location"), :input_html => {:style => "width: 400px;"	, :rows => 10} %>
</div>

<!-- Upload -->
<div class="section border">
	<% if @book.errors && @book.errors.messages[:document_content_type] %>
		<div class="control-group error">
			<label><%= @book.errors.messages[:document_content_type][0] %></label>
		</div>
	<% end %>
	<% if !book.new_record? && book.document.file? %>
	<h4><%= I18n.t("sb.forms.headers.update_attachment") %></h4>
		<div style="float:left;margin-right:10px"><%= image_tag("icons/file_pdf.png") %></div>
		<div>
			<%= book.document.original_filename %>&#160;
			<% if current_user.admin? -%>
				<%= link_to image_tag("icons/bin_empty.png"), destroy_document_book_path(book), 
					{:title => "Anhang löschen", 
					:confirm => "Willst Du diesen Anhang wirklich löschen?" } 
					%>
			<% end %>
		</div>
	<% else %>
		<h4><%= I18n.t("sb.forms.headers.add_attachment") %></h4>
	<% end %>
	<%= f.file_field :document, :label => I18n.t("sb.forms.labels.book_attachment"), 
		:style => "height:24px" %>
	<span class="help-block"><em><%= I18n.t("sb.forms.hints.book_attachment_type") %></em></span>
</div>

app/views/books/_list.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th class="number">Nr.</th>
			<th class="author">
				<%= link_to I18n.t("sb.tables.headers.author"), books_path + "?sort=author_last_name" + add_post_params(params), :title => I18n.t("sb.links.titles.sort_by_author") %>
				<%= add_order_arrow("author_last_name", params)%>
			</th>
			<th class="title">
				<%= link_to I18n.t("sb.tables.headers.book_title"), books_path + "?sort=title" + add_post_params(params), :title => I18n.t("sb.links.titles.sort_by_title") %>
				<%= add_order_arrow("title", params)%>
			</th>
			<th class="year">
				<%= link_to I18n.t("sb.tables.headers.book_year"), books_path + "?sort=year" + add_post_params(params), :title => I18n.t("sb.links.titles.sort_by_year") %>
				<%= add_order_arrow("year", params)%>
			</th>
			<th class="publisher">
				<%= link_to I18n.t("sb.tables.headers.book_publisher"), books_path + "?sort=publisher" + add_post_params(params), :title => I18n.t("sb.links.titles.sort_by_publisher") %>
				<%= add_order_arrow("publisher", params)%>
			</th>
			<th class="actions"></th>
		</tr>
	</thead>
	<tbody>
	<% if books.any? -%>
	<% books.each_with_index do |book,i| -%>
	<tr <%= (i.odd?) ? "class='odd'" : ""%>>
		<td><%= display_number(i) %></td>
		<td><%= display_linked_authors(book.authors) %></td>
		<td><%= link_to book.title, book_path(book), 
			:title => I18n.t("sb.links.titles.show_details") %>&#160;
			<%= image_tag("icons/file_pdf_small.png", 
				:title => I18n.t("sb.links.titles.book_attachment")) if book.document.file? %></td>
		<td><%= book.year %></td>
		<td><%= book.publisher %></td>
		<td class="buttons">
			<% if current_user.admin? -%>
				<%= button_to I18n.t("sb.forms.buttons.edit_book"),
					edit_book_path(book), 
					:title => I18n.t("sb.links.titles.edit_book"),
					:class => "btn edit-book",
					:method => :get %>
				<%= button_to I18n.t("sb.forms.buttons.delete_book"),
					book_path(book), 
					:method => :delete,
					:title => I18n.t("sb.links.titles.delete_book"),
					:class => "btn delete-book",
					:confirm => I18n.t("sb.links.confirms.delete_book") %>
			<% end %>
		</td>
	</tr>
	<% end -%>
	<% else -%>
		<tr>
			<td colspan="6"><%= I18n.t("sb.tables.books_no_results") %></td>
		</tr>
	<% end -%>
	</tbody>
</table>

app/views/books/_search.html.erb
<div class="grid_16 alpha">
<%= form_tag(books_path, {:class => "form", :method => :get}) do %>
	<div id="search">
		<div id="free_query">
			<%= text_field_tag "query", params[:query] || "" %>
			<%= hidden_field_tag "locale", params[:locale] || I18n.default_locale %>
			<%= submit_tag I18n.t("sb.buttons.search"), :class => "btn btn-primary" %>
		</div>
		<div class="row filters">
			<div class="span4">
				<label for="query"><%= I18n.t("sb.forms.labels.search.search_for") %></label>
				<%= check_box_tag "choices[title]", "1", 
					params["choices"] && params["choices"]["title"].present? || params["query"].blank? %>
					&#160;<%= I18n.t("sb.forms.labels.search.choice_title") %>
				<%= check_box_tag "choices[author]", "1", 
					params["choices"] && params["choices"]["author"].present? || params["query"].blank? %>
					&#160;<%= I18n.t("sb.forms.labels.search.choice_author") %>
				<%= check_box_tag "choices[publisher]", "1", 
					params["choices"] && params["choices"]["publisher"].present? || params["query"].blank?
					%>&#160;<%= I18n.t("sb.forms.labels.search.choice_publisher") %>
			</div>
			<div class="span4">
				<label for="book_format"><%= I18n.t("sb.forms.labels.search.filter_by_format") %></label>
				<%= select("book","format",Format.all(:order => "name ASC").collect{|option|[option.name,option.id]},{:selected => params[:book] && params[:book][:format] ? params[:book][:format] : 0, :include_blank => "-- Bitte auswählen --"})%>
			</div>
			<div class="span3">
				<%= partial "tag_in_use_selection"%>
				<%
				# Set selected tag on client because partial is cached 
				%>
				<script type="text/javascript" charset="utf-8">
					$(document).ready(function() {
						uri = URI(window.location.href).query(true);
						$('select#book_tag').val(parseInt(uri['book[tag]']));
						$('select#book_format').val(parseInt(uri['book[format]']));
					});
				</script>
			</div>
		</div>
	</div>
<% end -%>
</div>
<div class="clear"></div>

app/views/books/_tag_in_use_selection.html.erb
<% cache(:action => "new", :action_suffix => 'tag_in_use_selection') do %>
	<label for="book_nested_tags"><%= I18n.t("sb.forms.labels.search.filter_by_tag") %></label>
	<%= tree_select(NestedTag.root, "book", "tag", -1, "0", {:multiple => false, :filter_unused => true})%>
<% end %>

app/views/books/destroy.html.erb
<h1>BooksController#destroy</h1>
<p>Find me in app/views/books_controller/destroy.html.erb</p>

app/views/books/edit.html.erb
<% content_for(:head) do -%>
	<%= javascript_include_tag "simple-bookshelf/BookForm"%>
<% end -%>
<h2 style="margin-bottom:0"><%= I18n.t("sb.headers.new_book") %></h2>
<div style="margin-bottom:25px">
	<% if @book.updated_at %>
	<%= "#{I18n.t("sb.headers.book_updated_at")}: #{@book.updated_at.strftime("%d.%m.%Y, %H:%M:%S")}" %>
	<% end %>
</div>
<%= simple_form_for(@book, 
		:url => book_path(@book), :method => :put,
		:html => {:class => 'form_vertical', :id => 'edit_book_form', :multipart => true}) do |f| %>
	<%= partial "form", :book => @book, :f => f %>
	<%= f.submit I18n.t("sb.forms.buttons.update_book"), :class => "btn btn-primary" %>
<% end %>
<script type="text/javascript">
	new BookForm();
</script>

app/views/books/index.html.erb
<h2><%= I18n.t("sb.headers.book_list") %>
	<span class="total_entries">
		(<%= t('sb.headers.book_total_entries', :count => @books.total_entries) %>)
	</span>
</h2>
<%= partial "search", :current_tag_id => @current_tag_id %>
<%= partial "list", :books => @books %>
<%= will_paginate @books, 
	:previous_label => I18n.t("sb.will_paginate.previous_label"), 
	:next_label => I18n.t("sb.will_paginate.next_label"),
	:class => "pagination pagination-centered"
%>
<%= @params %>

app/views/books/new.html.erb
<% content_for(:head) do -%>
	<%= javascript_include_tag "simple-bookshelf/BookForm"%>
<% end -%>
<h2><%= I18n.t("sb.headers.new_book") %></h2>
<%= simple_form_for(@book, 
	:html => {:id => 'new_book_form', :class => 'form_vertical', :multipart => true}) do |f| %>
	<%= partial "form", :book => @book, :f => f %>
	<%= f.submit I18n.t("sb.forms.buttons.create_book"), :class => "btn btn-primary" %>
<% end -%>
<script type="text/javascript">
	BookForm.observeTitleField();
</script>

app/views/books/show.html.erb
<%= partial "details", :book => @book -%>

app/views/books/similar.html.erb
<% if @books && @books.any? -%>
<span class="header">Hinweis: Folgende Einträge mit ähnlichem Titel existieren bereits:</span>
<ul>
	<% for book in @books -%>
	<li><%= link_to book.title,book_path(book) %></li>
	<% end -%>
</ul>
<% end -%>